replicaCount: 1
image:
  repository: cr9ver/${{values.app_name}}
  pullPolicy: IfNotPresent
  tag: ${{values.app_name}}-${{values.app_env}}-latest


resources:
  requests:
    memory: "40m"
    cpu: "40m"